# Generated by Django 3.2.9 on 2021-12-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoulSgg',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('adm_sect_c', models.CharField(blank=True, max_length=254, null=True)),
                ('sgg_nm', models.CharField(blank=True, max_length=254, null=True)),
                ('sgg_oid', models.IntegerField(blank=True, null=True)),
                ('col_adm_se', models.CharField(blank=True, max_length=254, null=True)),
                ('field_gid', models.IntegerField(blank=True, db_column='__gid', null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seoul_sgg',
                'managed': False,
            },
        ),
    ]
