# Generated by Django 3.2.9 on 2021-12-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
