# Generated by Django 3.2.9 on 2021-12-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0008_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='authe_user',
        ),
    ]
