# Generated by Django 3.2.9 on 2021-12-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0009_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='authe_user1',
        ),
    ]
